//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BkTkts_btnBack {
            get {
                return ResourceManager.GetString("BkTkts_btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BkTkts_btnBackHome {
            get {
                return ResourceManager.GetString("BkTkts_btnBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BkTkts_btnBackToHome {
            get {
                return ResourceManager.GetString("BkTkts_btnBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BkTkts_btnClear {
            get {
                return ResourceManager.GetString("BkTkts_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BkTkts_btnClearDetails {
            get {
                return ResourceManager.GetString("BkTkts_btnClearDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string BkTkts_btnConfirm {
            get {
                return ResourceManager.GetString("BkTkts_btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BkTkts_btnSearchTrain {
            get {
                return ResourceManager.GetString("BkTkts_btnSearchTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string BkTkts_btnSelectTrain {
            get {
                return ResourceManager.GetString("BkTkts_btnSelectTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH RESULTS NOT FOUND.
        /// </summary>
        internal static string BkTkts_divSrchMsg {
            get {
                return ResourceManager.GetString("BkTkts_divSrchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string BkTkts_lblDate {
            get {
                return ResourceManager.GetString("BkTkts_lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Station.
        /// </summary>
        internal static string BkTkts_lblFromStation {
            get {
                return ResourceManager.GetString("BkTkts_lblFromStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Station.
        /// </summary>
        internal static string BkTkts_lblToStation {
            get {
                return ResourceManager.GetString("BkTkts_lblToStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Details.
        /// </summary>
        internal static string BkTkts_spnArrrivDets {
            get {
                return ResourceManager.GetString("BkTkts_spnArrrivDets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        internal static string BkTkts_spnArrvl {
            get {
                return ResourceManager.GetString("BkTkts_spnArrvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Details.
        /// </summary>
        internal static string BkTkts_spnDepartDets {
            get {
                return ResourceManager.GetString("BkTkts_spnDepartDets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string BkTkts_spnDept {
            get {
                return ResourceManager.GetString("BkTkts_spnDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket details sent to.
        /// </summary>
        internal static string BkTkts_spnEmailMsg {
            get {
                return ResourceManager.GetString("BkTkts_spnEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Station.
        /// </summary>
        internal static string BkTkts_spnFrmStn {
            get {
                return ResourceManager.GetString("BkTkts_spnFrmStn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string BkTkts_spnMail {
            get {
                return ResourceManager.GetString("BkTkts_spnMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string BkTkts_spnMobile {
            get {
                return ResourceManager.GetString("BkTkts_spnMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string BkTkts_spnMsg {
            get {
                return ResourceManager.GetString("BkTkts_spnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket(s) booked successfully.
        /// </summary>
        internal static string BkTkts_spnMsgAlert {
            get {
                return ResourceManager.GetString("BkTkts_spnMsgAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Train.
        /// </summary>
        internal static string BkTkts_spnSlctTrn {
            get {
                return ResourceManager.GetString("BkTkts_spnSlctTrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket No.:.
        /// </summary>
        internal static string BkTkts_spnTktNo {
            get {
                return ResourceManager.GetString("BkTkts_spnTktNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Station.
        /// </summary>
        internal static string BkTkts_spnToStn {
            get {
                return ResourceManager.GetString("BkTkts_spnToStn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Name.
        /// </summary>
        internal static string BkTkts_spnTrnNm {
            get {
                return ResourceManager.GetString("BkTkts_spnTrnNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Number.
        /// </summary>
        internal static string BkTkts_spnTrnNo {
            get {
                return ResourceManager.GetString("BkTkts_spnTrnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train No.
        /// </summary>
        internal static string BkTkts_spnTrnNum {
            get {
                return ResourceManager.GetString("BkTkts_spnTrnNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Trains.
        /// </summary>
        internal static string BkTkts_spnTrnSrch {
            get {
                return ResourceManager.GetString("BkTkts_spnTrnSrch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Details.
        /// </summary>
        internal static string BkTkts_spnTrvlDets {
            get {
                return ResourceManager.GetString("BkTkts_spnTrvlDets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel ID.
        /// </summary>
        internal static string BkTkts_spnTrvlId {
            get {
                return ResourceManager.GetString("BkTkts_spnTrvlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string BkTkts_spnUsrDetsUser {
            get {
                return ResourceManager.GetString("BkTkts_spnUsrDetsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triplicane High Road.
        /// </summary>
        internal static string mstr_spnAddr1 {
            get {
                return ResourceManager.GetString("mstr_spnAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triplicane, Chennai.
        /// </summary>
        internal static string mstr_spnAddr2 {
            get {
                return ResourceManager.GetString("mstr_spnAddr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string mstr_spnAddrTitle {
            get {
                return ResourceManager.GetString("mstr_spnAddrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string mstr_spnCntctTitle {
            get {
                return ResourceManager.GetString("mstr_spnCntctTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string mstr_spnCpyRts {
            get {
                return ResourceManager.GetString("mstr_spnCpyRts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string mstr_spnEmail {
            get {
                return ResourceManager.GetString("mstr_spnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string mstr_spnHomeText {
            get {
                return ResourceManager.GetString("mstr_spnHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string mstr_spnLangChng {
            get {
                return ResourceManager.GetString("mstr_spnLangChng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string mstr_spnPhone {
            get {
                return ResourceManager.GetString("mstr_spnPhone", resourceCulture);
            }
        }
    }
}
